// Copyright 2024 Dynatrace LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Portions of this code, as identified in remarks, are provided under the
// Creative Commons BY-SA or the MIT license, and are provided without
// any warranty. In each of the remarks, we have provided attribution to the
// original creators and other attribution parties, along with the title of
// the code (if known) a copyright notice and a link to the license, and a
// statement indicating whether or not we have modified the code.

import ExhaustedHacker from "../images/ExhaustedHacker.jpg";
import { FEEDBACK_MODAL_ID } from "../types/Common";

declare interface IEndCardProps {
  numQueries: number;
}

/**
 * Tells the user that he there are no more queries to show.
 */
function EndCard(props: Readonly<IEndCardProps>) {
  const { numQueries } = props;

  return (
    <div className="row">
      <div className="col-md-4">
        <figure className="figure">
          <img
            src={ExhaustedHacker}
            alt="Successful computer hacker, after reading hundreds of flashcards"
            className="img-fluid"
          />
          <figcaption className="figure-caption text-center">
            Generated by Midjourney prompt &raquo;&nbsp;successful computer
            hacker, after reading hundreds of flashcards&nbsp;&laquo;
          </figcaption>
        </figure>
      </div>
      <div className="col-lg-6">
        <p className="lead">
          Wow, after answering{" "}
          <strong>
            <mark>{numQueries} queries</mark>
          </strong>{" "}
          you actually reached the end of the game.{" "}
          <strong>
            Thank you so much for advancing research on cyber deception!
          </strong>
        </p>
        <p className="lead">
          Please consider coming back later when we have added more queries. You
          can tell your friends about Honeyquest in the meantime.
        </p>
        <p className="lead">
          If you want to improve Honeyquest or have any questions, send us some
          feedback or find our contact details at the bottom of this page.
        </p>
        <button
          type="button"
          className="btn btn-outline-primary mt-4"
          style={{ borderRadius: 0 }}
          data-bs-toggle="modal"
          data-bs-target={`#${FEEDBACK_MODAL_ID}`}
        >
          <i className="bi bi-chat-text"></i> Send feedback
        </button>
      </div>
    </div>
  );
}

export default EndCard;
